### ISSUE TITLE
`PWADevServer` file extension white list is problematic

### ISSUE THREAD

**Issue by DrewML** [magento-research/pwa-buildpack#32]
https://github.com/magento-research/pwa-buildpack/blob/f91f8aa5280424685cc9e71e237844be73a446c2/src/WebpackTools/PWADevServer.js#L161

We'll need to find a way to not have a whitelist of extensions. Consumers of this module will surely load other file types, and it won't be reasonable to require someone pass in all file extensions in the webpack config.

This is currently causing a 404 in [this PR](https://github.com/magento-research/venia-pwa-concept/pull/67) when loading a `.jpg` with `file-loader`.

**Comment by zetlen** [comment]
@DrewML Agreed! I have an idea for what to do about it: instead of using patterns to blacklist, we should use a filter function that checks whether a filename is in the current set of assets Webpack emitted on the last run. This means hooking into the compiler, so we've gotta figure that out.
